/**
 * generated by Xtext 2.12.0
 */
package de.uniluebeck.isp.tessla.ide;

import de.uniluebeck.isp.tessla.ide.AbstractTeSSLaIdeModule;

/**
 * Use this class to register ide components.
 */
@SuppressWarnings("all")
public class TeSSLaIdeModule extends AbstractTeSSLaIdeModule {
}
