/**
 * generated by Xtext 2.12.0
 */
package de.uniluebeck.isp.tessla.ui.contentassist;

import de.uniluebeck.isp.tessla.ui.contentassist.AbstractTeSSLaProposalProvider;

/**
 * See https://www.eclipse.org/Xtext/documentation/304_ide_concepts.html#content-assist
 * on how to customize the content assistant.
 */
@SuppressWarnings("all")
public class TeSSLaProposalProvider extends AbstractTeSSLaProposalProvider {
	
	
	
}
