/*
 * generated by Xtext 2.12.0
 */
package de.uniluebeck.isp.tessla.ui.tests;

import com.google.inject.Injector;
import de.uniluebeck.isp.tessla.ui.internal.TesslaActivator;
import org.eclipse.xtext.testing.IInjectorProvider;

public class TeSSLaUiInjectorProvider implements IInjectorProvider {

	@Override
	public Injector getInjector() {
		return TesslaActivator.getInstance().getInjector("de.uniluebeck.isp.tessla.TeSSLa");
	}

}
