/**
 * generated by Xtext 2.12.0
 */
package de.uniluebeck.isp.tessla.teSSLa;

import org.eclipse.emf.common.util.EList;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>definition</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link de.uniluebeck.isp.tessla.teSSLa.definition#getDef <em>Def</em>}</li>
 *   <li>{@link de.uniluebeck.isp.tessla.teSSLa.definition#getParamList <em>Param List</em>}</li>
 *   <li>{@link de.uniluebeck.isp.tessla.teSSLa.definition#getType <em>Type</em>}</li>
 *   <li>{@link de.uniluebeck.isp.tessla.teSSLa.definition#getExpression <em>Expression</em>}</li>
 *   <li>{@link de.uniluebeck.isp.tessla.teSSLa.definition#getStatements <em>Statements</em>}</li>
 * </ul>
 *
 * @see de.uniluebeck.isp.tessla.teSSLa.TeSSLaPackage#getdefinition()
 * @model
 * @generated
 */
public interface definition extends statement
{
  /**
   * Returns the value of the '<em><b>Def</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Def</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Def</em>' attribute.
   * @see #setDef(String)
   * @see de.uniluebeck.isp.tessla.teSSLa.TeSSLaPackage#getdefinition_Def()
   * @model
   * @generated
   */
  String getDef();

  /**
   * Sets the value of the '{@link de.uniluebeck.isp.tessla.teSSLa.definition#getDef <em>Def</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Def</em>' attribute.
   * @see #getDef()
   * @generated
   */
  void setDef(String value);

  /**
   * Returns the value of the '<em><b>Param List</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Param List</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Param List</em>' containment reference.
   * @see #setParamList(paramList)
   * @see de.uniluebeck.isp.tessla.teSSLa.TeSSLaPackage#getdefinition_ParamList()
   * @model containment="true"
   * @generated
   */
  paramList getParamList();

  /**
   * Sets the value of the '{@link de.uniluebeck.isp.tessla.teSSLa.definition#getParamList <em>Param List</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Param List</em>' containment reference.
   * @see #getParamList()
   * @generated
   */
  void setParamList(paramList value);

  /**
   * Returns the value of the '<em><b>Type</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Type</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Type</em>' attribute.
   * @see #setType(String)
   * @see de.uniluebeck.isp.tessla.teSSLa.TeSSLaPackage#getdefinition_Type()
   * @model
   * @generated
   */
  String getType();

  /**
   * Sets the value of the '{@link de.uniluebeck.isp.tessla.teSSLa.definition#getType <em>Type</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Type</em>' attribute.
   * @see #getType()
   * @generated
   */
  void setType(String value);

  /**
   * Returns the value of the '<em><b>Expression</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Expression</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Expression</em>' containment reference.
   * @see #setExpression(expression)
   * @see de.uniluebeck.isp.tessla.teSSLa.TeSSLaPackage#getdefinition_Expression()
   * @model containment="true"
   * @generated
   */
  expression getExpression();

  /**
   * Sets the value of the '{@link de.uniluebeck.isp.tessla.teSSLa.definition#getExpression <em>Expression</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Expression</em>' containment reference.
   * @see #getExpression()
   * @generated
   */
  void setExpression(expression value);

  /**
   * Returns the value of the '<em><b>Statements</b></em>' containment reference list.
   * The list contents are of type {@link de.uniluebeck.isp.tessla.teSSLa.statement}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Statements</em>' containment reference list isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Statements</em>' containment reference list.
   * @see de.uniluebeck.isp.tessla.teSSLa.TeSSLaPackage#getdefinition_Statements()
   * @model containment="true"
   * @generated
   */
  EList<statement> getStatements();

} // definition
