/**
 * generated by Xtext 2.12.0
 */
package de.uniluebeck.isp.tessla.teSSLa;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>expression</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link de.uniluebeck.isp.tessla.teSSLa.expression#getInfix <em>Infix</em>}</li>
 *   <li>{@link de.uniluebeck.isp.tessla.teSSLa.expression#getType <em>Type</em>}</li>
 * </ul>
 *
 * @see de.uniluebeck.isp.tessla.teSSLa.TeSSLaPackage#getexpression()
 * @model
 * @generated
 */
public interface expression extends EObject
{
  /**
   * Returns the value of the '<em><b>Infix</b></em>' containment reference list.
   * The list contents are of type {@link de.uniluebeck.isp.tessla.teSSLa.expInfix}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Infix</em>' containment reference list isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Infix</em>' containment reference list.
   * @see de.uniluebeck.isp.tessla.teSSLa.TeSSLaPackage#getexpression_Infix()
   * @model containment="true"
   * @generated
   */
  EList<expInfix> getInfix();

  /**
   * Returns the value of the '<em><b>Type</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Type</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Type</em>' attribute.
   * @see #setType(String)
   * @see de.uniluebeck.isp.tessla.teSSLa.TeSSLaPackage#getexpression_Type()
   * @model
   * @generated
   */
  String getType();

  /**
   * Sets the value of the '{@link de.uniluebeck.isp.tessla.teSSLa.expression#getType <em>Type</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Type</em>' attribute.
   * @see #getType()
   * @generated
   */
  void setType(String value);

} // expression
