/**
 * generated by Xtext 2.12.0
 */
package de.uniluebeck.isp.tessla.teSSLa;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>statement</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see de.uniluebeck.isp.tessla.teSSLa.TeSSLaPackage#getstatement()
 * @model
 * @generated
 */
public interface statement extends EObject
{
} // statement
