/**
 * generated by Xtext 2.12.0
 */
package de.uniluebeck.isp.tessla.teSSLa;

import org.eclipse.emf.ecore.EAttribute;
import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.emf.ecore.EReference;

/**
 * <!-- begin-user-doc -->
 * The <b>Package</b> for the model.
 * It contains accessors for the meta objects to represent
 * <ul>
 *   <li>each class,</li>
 *   <li>each feature of each class,</li>
 *   <li>each enum,</li>
 *   <li>and each data type</li>
 * </ul>
 * <!-- end-user-doc -->
 * @see de.uniluebeck.isp.tessla.teSSLa.TeSSLaFactory
 * @model kind="package"
 * @generated
 */
public interface TeSSLaPackage extends EPackage
{
  /**
   * The package name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNAME = "teSSLa";

  /**
   * The package namespace URI.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_URI = "http://www.uniluebeck.de/isp/tessla/TeSSLa";

  /**
   * The package namespace name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_PREFIX = "teSSLa";

  /**
   * The singleton instance of the package.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  TeSSLaPackage eINSTANCE = de.uniluebeck.isp.tessla.teSSLa.impl.TeSSLaPackageImpl.init();

  /**
   * The meta object id for the '{@link de.uniluebeck.isp.tessla.teSSLa.impl.ModelImpl <em>Model</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see de.uniluebeck.isp.tessla.teSSLa.impl.ModelImpl
   * @see de.uniluebeck.isp.tessla.teSSLa.impl.TeSSLaPackageImpl#getModel()
   * @generated
   */
  int MODEL = 0;

  /**
   * The feature id for the '<em><b>Spec</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MODEL__SPEC = 0;

  /**
   * The number of structural features of the '<em>Model</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MODEL_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link de.uniluebeck.isp.tessla.teSSLa.impl.statementImpl <em>statement</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see de.uniluebeck.isp.tessla.teSSLa.impl.statementImpl
   * @see de.uniluebeck.isp.tessla.teSSLa.impl.TeSSLaPackageImpl#getstatement()
   * @generated
   */
  int STATEMENT = 1;

  /**
   * The number of structural features of the '<em>statement</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int STATEMENT_FEATURE_COUNT = 0;

  /**
   * The meta object id for the '{@link de.uniluebeck.isp.tessla.teSSLa.impl.definitionImpl <em>definition</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see de.uniluebeck.isp.tessla.teSSLa.impl.definitionImpl
   * @see de.uniluebeck.isp.tessla.teSSLa.impl.TeSSLaPackageImpl#getdefinition()
   * @generated
   */
  int DEFINITION = 2;

  /**
   * The feature id for the '<em><b>Def</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DEFINITION__DEF = STATEMENT_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Param List</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DEFINITION__PARAM_LIST = STATEMENT_FEATURE_COUNT + 1;

  /**
   * The feature id for the '<em><b>Type</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DEFINITION__TYPE = STATEMENT_FEATURE_COUNT + 2;

  /**
   * The feature id for the '<em><b>Expression</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DEFINITION__EXPRESSION = STATEMENT_FEATURE_COUNT + 3;

  /**
   * The feature id for the '<em><b>Statements</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DEFINITION__STATEMENTS = STATEMENT_FEATURE_COUNT + 4;

  /**
   * The number of structural features of the '<em>definition</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DEFINITION_FEATURE_COUNT = STATEMENT_FEATURE_COUNT + 5;

  /**
   * The meta object id for the '{@link de.uniluebeck.isp.tessla.teSSLa.impl.paramListImpl <em>param List</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see de.uniluebeck.isp.tessla.teSSLa.impl.paramListImpl
   * @see de.uniluebeck.isp.tessla.teSSLa.impl.TeSSLaPackageImpl#getparamList()
   * @generated
   */
  int PARAM_LIST = 3;

  /**
   * The feature id for the '<em><b>Params</b></em>' attribute list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PARAM_LIST__PARAMS = 0;

  /**
   * The feature id for the '<em><b>Types</b></em>' attribute list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PARAM_LIST__TYPES = 1;

  /**
   * The number of structural features of the '<em>param List</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PARAM_LIST_FEATURE_COUNT = 2;

  /**
   * The meta object id for the '{@link de.uniluebeck.isp.tessla.teSSLa.impl.outImpl <em>out</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see de.uniluebeck.isp.tessla.teSSLa.impl.outImpl
   * @see de.uniluebeck.isp.tessla.teSSLa.impl.TeSSLaPackageImpl#getout()
   * @generated
   */
  int OUT = 4;

  /**
   * The feature id for the '<em><b>Expression</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int OUT__EXPRESSION = STATEMENT_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int OUT__NAME = STATEMENT_FEATURE_COUNT + 1;

  /**
   * The number of structural features of the '<em>out</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int OUT_FEATURE_COUNT = STATEMENT_FEATURE_COUNT + 2;

  /**
   * The meta object id for the '{@link de.uniluebeck.isp.tessla.teSSLa.impl.inImpl <em>in</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see de.uniluebeck.isp.tessla.teSSLa.impl.inImpl
   * @see de.uniluebeck.isp.tessla.teSSLa.impl.TeSSLaPackageImpl#getin()
   * @generated
   */
  int IN = 5;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int IN__NAME = STATEMENT_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Type</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int IN__TYPE = STATEMENT_FEATURE_COUNT + 1;

  /**
   * The number of structural features of the '<em>in</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int IN_FEATURE_COUNT = STATEMENT_FEATURE_COUNT + 2;

  /**
   * The meta object id for the '{@link de.uniluebeck.isp.tessla.teSSLa.impl.expressionImpl <em>expression</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see de.uniluebeck.isp.tessla.teSSLa.impl.expressionImpl
   * @see de.uniluebeck.isp.tessla.teSSLa.impl.TeSSLaPackageImpl#getexpression()
   * @generated
   */
  int EXPRESSION = 6;

  /**
   * The feature id for the '<em><b>Infix</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int EXPRESSION__INFIX = 0;

  /**
   * The feature id for the '<em><b>Type</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int EXPRESSION__TYPE = 1;

  /**
   * The number of structural features of the '<em>expression</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int EXPRESSION_FEATURE_COUNT = 2;

  /**
   * The meta object id for the '{@link de.uniluebeck.isp.tessla.teSSLa.impl.expInfixImpl <em>exp Infix</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see de.uniluebeck.isp.tessla.teSSLa.impl.expInfixImpl
   * @see de.uniluebeck.isp.tessla.teSSLa.impl.TeSSLaPackageImpl#getexpInfix()
   * @generated
   */
  int EXP_INFIX = 7;

  /**
   * The feature id for the '<em><b>Unary</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int EXP_INFIX__UNARY = 0;

  /**
   * The feature id for the '<em><b>Operator</b></em>' attribute list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int EXP_INFIX__OPERATOR = 1;

  /**
   * The feature id for the '<em><b>Type</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int EXP_INFIX__TYPE = 2;

  /**
   * The number of structural features of the '<em>exp Infix</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int EXP_INFIX_FEATURE_COUNT = 3;

  /**
   * The meta object id for the '{@link de.uniluebeck.isp.tessla.teSSLa.impl.expUnaryImpl <em>exp Unary</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see de.uniluebeck.isp.tessla.teSSLa.impl.expUnaryImpl
   * @see de.uniluebeck.isp.tessla.teSSLa.impl.TeSSLaPackageImpl#getexpUnary()
   * @generated
   */
  int EXP_UNARY = 8;

  /**
   * The feature id for the '<em><b>Operator</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int EXP_UNARY__OPERATOR = 0;

  /**
   * The feature id for the '<em><b>Value</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int EXP_UNARY__VALUE = 1;

  /**
   * The feature id for the '<em><b>Type</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int EXP_UNARY__TYPE = 2;

  /**
   * The number of structural features of the '<em>exp Unary</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int EXP_UNARY_FEATURE_COUNT = 3;

  /**
   * The meta object id for the '{@link de.uniluebeck.isp.tessla.teSSLa.impl.expFuncImpl <em>exp Func</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see de.uniluebeck.isp.tessla.teSSLa.impl.expFuncImpl
   * @see de.uniluebeck.isp.tessla.teSSLa.impl.TeSSLaPackageImpl#getexpFunc()
   * @generated
   */
  int EXP_FUNC = 9;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int EXP_FUNC__NAME = 0;

  /**
   * The feature id for the '<em><b>Params</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int EXP_FUNC__PARAMS = 1;

  /**
   * The feature id for the '<em><b>Type</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int EXP_FUNC__TYPE = 2;

  /**
   * The number of structural features of the '<em>exp Func</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int EXP_FUNC_FEATURE_COUNT = 3;


  /**
   * Returns the meta object for class '{@link de.uniluebeck.isp.tessla.teSSLa.Model <em>Model</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Model</em>'.
   * @see de.uniluebeck.isp.tessla.teSSLa.Model
   * @generated
   */
  EClass getModel();

  /**
   * Returns the meta object for the containment reference list '{@link de.uniluebeck.isp.tessla.teSSLa.Model#getSpec <em>Spec</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Spec</em>'.
   * @see de.uniluebeck.isp.tessla.teSSLa.Model#getSpec()
   * @see #getModel()
   * @generated
   */
  EReference getModel_Spec();

  /**
   * Returns the meta object for class '{@link de.uniluebeck.isp.tessla.teSSLa.statement <em>statement</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>statement</em>'.
   * @see de.uniluebeck.isp.tessla.teSSLa.statement
   * @generated
   */
  EClass getstatement();

  /**
   * Returns the meta object for class '{@link de.uniluebeck.isp.tessla.teSSLa.definition <em>definition</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>definition</em>'.
   * @see de.uniluebeck.isp.tessla.teSSLa.definition
   * @generated
   */
  EClass getdefinition();

  /**
   * Returns the meta object for the attribute '{@link de.uniluebeck.isp.tessla.teSSLa.definition#getDef <em>Def</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Def</em>'.
   * @see de.uniluebeck.isp.tessla.teSSLa.definition#getDef()
   * @see #getdefinition()
   * @generated
   */
  EAttribute getdefinition_Def();

  /**
   * Returns the meta object for the containment reference '{@link de.uniluebeck.isp.tessla.teSSLa.definition#getParamList <em>Param List</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Param List</em>'.
   * @see de.uniluebeck.isp.tessla.teSSLa.definition#getParamList()
   * @see #getdefinition()
   * @generated
   */
  EReference getdefinition_ParamList();

  /**
   * Returns the meta object for the attribute '{@link de.uniluebeck.isp.tessla.teSSLa.definition#getType <em>Type</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Type</em>'.
   * @see de.uniluebeck.isp.tessla.teSSLa.definition#getType()
   * @see #getdefinition()
   * @generated
   */
  EAttribute getdefinition_Type();

  /**
   * Returns the meta object for the containment reference '{@link de.uniluebeck.isp.tessla.teSSLa.definition#getExpression <em>Expression</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Expression</em>'.
   * @see de.uniluebeck.isp.tessla.teSSLa.definition#getExpression()
   * @see #getdefinition()
   * @generated
   */
  EReference getdefinition_Expression();

  /**
   * Returns the meta object for the containment reference list '{@link de.uniluebeck.isp.tessla.teSSLa.definition#getStatements <em>Statements</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Statements</em>'.
   * @see de.uniluebeck.isp.tessla.teSSLa.definition#getStatements()
   * @see #getdefinition()
   * @generated
   */
  EReference getdefinition_Statements();

  /**
   * Returns the meta object for class '{@link de.uniluebeck.isp.tessla.teSSLa.paramList <em>param List</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>param List</em>'.
   * @see de.uniluebeck.isp.tessla.teSSLa.paramList
   * @generated
   */
  EClass getparamList();

  /**
   * Returns the meta object for the attribute list '{@link de.uniluebeck.isp.tessla.teSSLa.paramList#getParams <em>Params</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute list '<em>Params</em>'.
   * @see de.uniluebeck.isp.tessla.teSSLa.paramList#getParams()
   * @see #getparamList()
   * @generated
   */
  EAttribute getparamList_Params();

  /**
   * Returns the meta object for the attribute list '{@link de.uniluebeck.isp.tessla.teSSLa.paramList#getTypes <em>Types</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute list '<em>Types</em>'.
   * @see de.uniluebeck.isp.tessla.teSSLa.paramList#getTypes()
   * @see #getparamList()
   * @generated
   */
  EAttribute getparamList_Types();

  /**
   * Returns the meta object for class '{@link de.uniluebeck.isp.tessla.teSSLa.out <em>out</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>out</em>'.
   * @see de.uniluebeck.isp.tessla.teSSLa.out
   * @generated
   */
  EClass getout();

  /**
   * Returns the meta object for the containment reference '{@link de.uniluebeck.isp.tessla.teSSLa.out#getExpression <em>Expression</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Expression</em>'.
   * @see de.uniluebeck.isp.tessla.teSSLa.out#getExpression()
   * @see #getout()
   * @generated
   */
  EReference getout_Expression();

  /**
   * Returns the meta object for the attribute '{@link de.uniluebeck.isp.tessla.teSSLa.out#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see de.uniluebeck.isp.tessla.teSSLa.out#getName()
   * @see #getout()
   * @generated
   */
  EAttribute getout_Name();

  /**
   * Returns the meta object for class '{@link de.uniluebeck.isp.tessla.teSSLa.in <em>in</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>in</em>'.
   * @see de.uniluebeck.isp.tessla.teSSLa.in
   * @generated
   */
  EClass getin();

  /**
   * Returns the meta object for the attribute '{@link de.uniluebeck.isp.tessla.teSSLa.in#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see de.uniluebeck.isp.tessla.teSSLa.in#getName()
   * @see #getin()
   * @generated
   */
  EAttribute getin_Name();

  /**
   * Returns the meta object for the attribute '{@link de.uniluebeck.isp.tessla.teSSLa.in#getType <em>Type</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Type</em>'.
   * @see de.uniluebeck.isp.tessla.teSSLa.in#getType()
   * @see #getin()
   * @generated
   */
  EAttribute getin_Type();

  /**
   * Returns the meta object for class '{@link de.uniluebeck.isp.tessla.teSSLa.expression <em>expression</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>expression</em>'.
   * @see de.uniluebeck.isp.tessla.teSSLa.expression
   * @generated
   */
  EClass getexpression();

  /**
   * Returns the meta object for the containment reference list '{@link de.uniluebeck.isp.tessla.teSSLa.expression#getInfix <em>Infix</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Infix</em>'.
   * @see de.uniluebeck.isp.tessla.teSSLa.expression#getInfix()
   * @see #getexpression()
   * @generated
   */
  EReference getexpression_Infix();

  /**
   * Returns the meta object for the attribute '{@link de.uniluebeck.isp.tessla.teSSLa.expression#getType <em>Type</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Type</em>'.
   * @see de.uniluebeck.isp.tessla.teSSLa.expression#getType()
   * @see #getexpression()
   * @generated
   */
  EAttribute getexpression_Type();

  /**
   * Returns the meta object for class '{@link de.uniluebeck.isp.tessla.teSSLa.expInfix <em>exp Infix</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>exp Infix</em>'.
   * @see de.uniluebeck.isp.tessla.teSSLa.expInfix
   * @generated
   */
  EClass getexpInfix();

  /**
   * Returns the meta object for the containment reference list '{@link de.uniluebeck.isp.tessla.teSSLa.expInfix#getUnary <em>Unary</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Unary</em>'.
   * @see de.uniluebeck.isp.tessla.teSSLa.expInfix#getUnary()
   * @see #getexpInfix()
   * @generated
   */
  EReference getexpInfix_Unary();

  /**
   * Returns the meta object for the attribute list '{@link de.uniluebeck.isp.tessla.teSSLa.expInfix#getOperator <em>Operator</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute list '<em>Operator</em>'.
   * @see de.uniluebeck.isp.tessla.teSSLa.expInfix#getOperator()
   * @see #getexpInfix()
   * @generated
   */
  EAttribute getexpInfix_Operator();

  /**
   * Returns the meta object for the attribute '{@link de.uniluebeck.isp.tessla.teSSLa.expInfix#getType <em>Type</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Type</em>'.
   * @see de.uniluebeck.isp.tessla.teSSLa.expInfix#getType()
   * @see #getexpInfix()
   * @generated
   */
  EAttribute getexpInfix_Type();

  /**
   * Returns the meta object for class '{@link de.uniluebeck.isp.tessla.teSSLa.expUnary <em>exp Unary</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>exp Unary</em>'.
   * @see de.uniluebeck.isp.tessla.teSSLa.expUnary
   * @generated
   */
  EClass getexpUnary();

  /**
   * Returns the meta object for the attribute '{@link de.uniluebeck.isp.tessla.teSSLa.expUnary#getOperator <em>Operator</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Operator</em>'.
   * @see de.uniluebeck.isp.tessla.teSSLa.expUnary#getOperator()
   * @see #getexpUnary()
   * @generated
   */
  EAttribute getexpUnary_Operator();

  /**
   * Returns the meta object for the containment reference '{@link de.uniluebeck.isp.tessla.teSSLa.expUnary#getValue <em>Value</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Value</em>'.
   * @see de.uniluebeck.isp.tessla.teSSLa.expUnary#getValue()
   * @see #getexpUnary()
   * @generated
   */
  EReference getexpUnary_Value();

  /**
   * Returns the meta object for the attribute '{@link de.uniluebeck.isp.tessla.teSSLa.expUnary#getType <em>Type</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Type</em>'.
   * @see de.uniluebeck.isp.tessla.teSSLa.expUnary#getType()
   * @see #getexpUnary()
   * @generated
   */
  EAttribute getexpUnary_Type();

  /**
   * Returns the meta object for class '{@link de.uniluebeck.isp.tessla.teSSLa.expFunc <em>exp Func</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>exp Func</em>'.
   * @see de.uniluebeck.isp.tessla.teSSLa.expFunc
   * @generated
   */
  EClass getexpFunc();

  /**
   * Returns the meta object for the attribute '{@link de.uniluebeck.isp.tessla.teSSLa.expFunc#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see de.uniluebeck.isp.tessla.teSSLa.expFunc#getName()
   * @see #getexpFunc()
   * @generated
   */
  EAttribute getexpFunc_Name();

  /**
   * Returns the meta object for the containment reference list '{@link de.uniluebeck.isp.tessla.teSSLa.expFunc#getParams <em>Params</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Params</em>'.
   * @see de.uniluebeck.isp.tessla.teSSLa.expFunc#getParams()
   * @see #getexpFunc()
   * @generated
   */
  EReference getexpFunc_Params();

  /**
   * Returns the meta object for the attribute '{@link de.uniluebeck.isp.tessla.teSSLa.expFunc#getType <em>Type</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Type</em>'.
   * @see de.uniluebeck.isp.tessla.teSSLa.expFunc#getType()
   * @see #getexpFunc()
   * @generated
   */
  EAttribute getexpFunc_Type();

  /**
   * Returns the factory that creates the instances of the model.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the factory that creates the instances of the model.
   * @generated
   */
  TeSSLaFactory getTeSSLaFactory();

  /**
   * <!-- begin-user-doc -->
   * Defines literals for the meta objects that represent
   * <ul>
   *   <li>each class,</li>
   *   <li>each feature of each class,</li>
   *   <li>each enum,</li>
   *   <li>and each data type</li>
   * </ul>
   * <!-- end-user-doc -->
   * @generated
   */
  interface Literals
  {
    /**
     * The meta object literal for the '{@link de.uniluebeck.isp.tessla.teSSLa.impl.ModelImpl <em>Model</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see de.uniluebeck.isp.tessla.teSSLa.impl.ModelImpl
     * @see de.uniluebeck.isp.tessla.teSSLa.impl.TeSSLaPackageImpl#getModel()
     * @generated
     */
    EClass MODEL = eINSTANCE.getModel();

    /**
     * The meta object literal for the '<em><b>Spec</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference MODEL__SPEC = eINSTANCE.getModel_Spec();

    /**
     * The meta object literal for the '{@link de.uniluebeck.isp.tessla.teSSLa.impl.statementImpl <em>statement</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see de.uniluebeck.isp.tessla.teSSLa.impl.statementImpl
     * @see de.uniluebeck.isp.tessla.teSSLa.impl.TeSSLaPackageImpl#getstatement()
     * @generated
     */
    EClass STATEMENT = eINSTANCE.getstatement();

    /**
     * The meta object literal for the '{@link de.uniluebeck.isp.tessla.teSSLa.impl.definitionImpl <em>definition</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see de.uniluebeck.isp.tessla.teSSLa.impl.definitionImpl
     * @see de.uniluebeck.isp.tessla.teSSLa.impl.TeSSLaPackageImpl#getdefinition()
     * @generated
     */
    EClass DEFINITION = eINSTANCE.getdefinition();

    /**
     * The meta object literal for the '<em><b>Def</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute DEFINITION__DEF = eINSTANCE.getdefinition_Def();

    /**
     * The meta object literal for the '<em><b>Param List</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference DEFINITION__PARAM_LIST = eINSTANCE.getdefinition_ParamList();

    /**
     * The meta object literal for the '<em><b>Type</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute DEFINITION__TYPE = eINSTANCE.getdefinition_Type();

    /**
     * The meta object literal for the '<em><b>Expression</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference DEFINITION__EXPRESSION = eINSTANCE.getdefinition_Expression();

    /**
     * The meta object literal for the '<em><b>Statements</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference DEFINITION__STATEMENTS = eINSTANCE.getdefinition_Statements();

    /**
     * The meta object literal for the '{@link de.uniluebeck.isp.tessla.teSSLa.impl.paramListImpl <em>param List</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see de.uniluebeck.isp.tessla.teSSLa.impl.paramListImpl
     * @see de.uniluebeck.isp.tessla.teSSLa.impl.TeSSLaPackageImpl#getparamList()
     * @generated
     */
    EClass PARAM_LIST = eINSTANCE.getparamList();

    /**
     * The meta object literal for the '<em><b>Params</b></em>' attribute list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute PARAM_LIST__PARAMS = eINSTANCE.getparamList_Params();

    /**
     * The meta object literal for the '<em><b>Types</b></em>' attribute list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute PARAM_LIST__TYPES = eINSTANCE.getparamList_Types();

    /**
     * The meta object literal for the '{@link de.uniluebeck.isp.tessla.teSSLa.impl.outImpl <em>out</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see de.uniluebeck.isp.tessla.teSSLa.impl.outImpl
     * @see de.uniluebeck.isp.tessla.teSSLa.impl.TeSSLaPackageImpl#getout()
     * @generated
     */
    EClass OUT = eINSTANCE.getout();

    /**
     * The meta object literal for the '<em><b>Expression</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference OUT__EXPRESSION = eINSTANCE.getout_Expression();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute OUT__NAME = eINSTANCE.getout_Name();

    /**
     * The meta object literal for the '{@link de.uniluebeck.isp.tessla.teSSLa.impl.inImpl <em>in</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see de.uniluebeck.isp.tessla.teSSLa.impl.inImpl
     * @see de.uniluebeck.isp.tessla.teSSLa.impl.TeSSLaPackageImpl#getin()
     * @generated
     */
    EClass IN = eINSTANCE.getin();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute IN__NAME = eINSTANCE.getin_Name();

    /**
     * The meta object literal for the '<em><b>Type</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute IN__TYPE = eINSTANCE.getin_Type();

    /**
     * The meta object literal for the '{@link de.uniluebeck.isp.tessla.teSSLa.impl.expressionImpl <em>expression</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see de.uniluebeck.isp.tessla.teSSLa.impl.expressionImpl
     * @see de.uniluebeck.isp.tessla.teSSLa.impl.TeSSLaPackageImpl#getexpression()
     * @generated
     */
    EClass EXPRESSION = eINSTANCE.getexpression();

    /**
     * The meta object literal for the '<em><b>Infix</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference EXPRESSION__INFIX = eINSTANCE.getexpression_Infix();

    /**
     * The meta object literal for the '<em><b>Type</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute EXPRESSION__TYPE = eINSTANCE.getexpression_Type();

    /**
     * The meta object literal for the '{@link de.uniluebeck.isp.tessla.teSSLa.impl.expInfixImpl <em>exp Infix</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see de.uniluebeck.isp.tessla.teSSLa.impl.expInfixImpl
     * @see de.uniluebeck.isp.tessla.teSSLa.impl.TeSSLaPackageImpl#getexpInfix()
     * @generated
     */
    EClass EXP_INFIX = eINSTANCE.getexpInfix();

    /**
     * The meta object literal for the '<em><b>Unary</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference EXP_INFIX__UNARY = eINSTANCE.getexpInfix_Unary();

    /**
     * The meta object literal for the '<em><b>Operator</b></em>' attribute list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute EXP_INFIX__OPERATOR = eINSTANCE.getexpInfix_Operator();

    /**
     * The meta object literal for the '<em><b>Type</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute EXP_INFIX__TYPE = eINSTANCE.getexpInfix_Type();

    /**
     * The meta object literal for the '{@link de.uniluebeck.isp.tessla.teSSLa.impl.expUnaryImpl <em>exp Unary</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see de.uniluebeck.isp.tessla.teSSLa.impl.expUnaryImpl
     * @see de.uniluebeck.isp.tessla.teSSLa.impl.TeSSLaPackageImpl#getexpUnary()
     * @generated
     */
    EClass EXP_UNARY = eINSTANCE.getexpUnary();

    /**
     * The meta object literal for the '<em><b>Operator</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute EXP_UNARY__OPERATOR = eINSTANCE.getexpUnary_Operator();

    /**
     * The meta object literal for the '<em><b>Value</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference EXP_UNARY__VALUE = eINSTANCE.getexpUnary_Value();

    /**
     * The meta object literal for the '<em><b>Type</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute EXP_UNARY__TYPE = eINSTANCE.getexpUnary_Type();

    /**
     * The meta object literal for the '{@link de.uniluebeck.isp.tessla.teSSLa.impl.expFuncImpl <em>exp Func</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see de.uniluebeck.isp.tessla.teSSLa.impl.expFuncImpl
     * @see de.uniluebeck.isp.tessla.teSSLa.impl.TeSSLaPackageImpl#getexpFunc()
     * @generated
     */
    EClass EXP_FUNC = eINSTANCE.getexpFunc();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute EXP_FUNC__NAME = eINSTANCE.getexpFunc_Name();

    /**
     * The meta object literal for the '<em><b>Params</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference EXP_FUNC__PARAMS = eINSTANCE.getexpFunc_Params();

    /**
     * The meta object literal for the '<em><b>Type</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute EXP_FUNC__TYPE = eINSTANCE.getexpFunc_Type();

  }

} //TeSSLaPackage
