/*
 * generated by Xtext 2.12.0
 */
package de.uniluebeck.isp.tessla.parser.antlr;

import java.io.InputStream;
import org.eclipse.xtext.parser.antlr.IAntlrTokenFileProvider;

public class TeSSLaAntlrTokenFileProvider implements IAntlrTokenFileProvider {

	@Override
	public InputStream getAntlrTokenFile() {
		ClassLoader classLoader = getClass().getClassLoader();
		return classLoader.getResourceAsStream("de/uniluebeck/isp/tessla/parser/antlr/internal/InternalTeSSLa.tokens");
	}
}
