/*
 * generated by Xtext 2.12.0
 */
package de.uniluebeck.isp.tessla.serializer;

import com.google.inject.Inject;
import de.uniluebeck.isp.tessla.services.TeSSLaGrammarAccess;
import java.util.List;
import org.eclipse.emf.ecore.EObject;
import org.eclipse.xtext.IGrammarAccess;
import org.eclipse.xtext.RuleCall;
import org.eclipse.xtext.nodemodel.INode;
import org.eclipse.xtext.serializer.analysis.GrammarAlias.AbstractElementAlias;
import org.eclipse.xtext.serializer.analysis.GrammarAlias.AlternativeAlias;
import org.eclipse.xtext.serializer.analysis.GrammarAlias.GroupAlias;
import org.eclipse.xtext.serializer.analysis.GrammarAlias.TokenAlias;
import org.eclipse.xtext.serializer.analysis.ISyntacticSequencerPDAProvider.ISynNavigable;
import org.eclipse.xtext.serializer.analysis.ISyntacticSequencerPDAProvider.ISynTransition;
import org.eclipse.xtext.serializer.sequencer.AbstractSyntacticSequencer;

@SuppressWarnings("all")
public class TeSSLaSyntacticSequencer extends AbstractSyntacticSequencer {

	protected TeSSLaGrammarAccess grammarAccess;
	protected AbstractElementAlias match_definition_DefKeyword_0_0_or_DefineKeyword_0_1;
	protected AbstractElementAlias match_expression___IDTerminalRuleCall_1_0_EqualsSignKeyword_1_1__a;
	
	@Inject
	protected void init(IGrammarAccess access) {
		grammarAccess = (TeSSLaGrammarAccess) access;
		match_definition_DefKeyword_0_0_or_DefineKeyword_0_1 = new AlternativeAlias(false, false, new TokenAlias(false, false, grammarAccess.getDefinitionAccess().getDefKeyword_0_0()), new TokenAlias(false, false, grammarAccess.getDefinitionAccess().getDefineKeyword_0_1()));
		match_expression___IDTerminalRuleCall_1_0_EqualsSignKeyword_1_1__a = new GroupAlias(true, true, new TokenAlias(false, false, grammarAccess.getExpressionAccess().getIDTerminalRuleCall_1_0()), new TokenAlias(false, false, grammarAccess.getExpressionAccess().getEqualsSignKeyword_1_1()));
	}
	
	@Override
	protected String getUnassignedRuleCallToken(EObject semanticObject, RuleCall ruleCall, INode node) {
		if (ruleCall.getRule() == grammarAccess.getIDRule())
			return getIDToken(semanticObject, ruleCall, node);
		else if (ruleCall.getRule() == grammarAccess.getSL_COMMENTRule())
			return getSL_COMMENTToken(semanticObject, ruleCall, node);
		return "";
	}
	
	/**
	 * terminal ID  		: '^'?('a'..'z'|'A'..'Z'|'_') ('a'..'z'|'A'..'Z'|'_'|'0'..'9')*;
	 */
	protected String getIDToken(EObject semanticObject, RuleCall ruleCall, INode node) {
		if (node != null)
			return getTokenText(node);
		return "";
	}
	
	/**
	 * @Override 
	 * terminal SL_COMMENT:
	 *     ('--') !('\n'|'\r')* ('\r'? '\n')?
	 * ;
	 */
	protected String getSL_COMMENTToken(EObject semanticObject, RuleCall ruleCall, INode node) {
		if (node != null)
			return getTokenText(node);
		return "--";
	}
	
	@Override
	protected void emitUnassignedTokens(EObject semanticObject, ISynTransition transition, INode fromNode, INode toNode) {
		if (transition.getAmbiguousSyntaxes().isEmpty()) return;
		List<INode> transitionNodes = collectNodes(fromNode, toNode);
		for (AbstractElementAlias syntax : transition.getAmbiguousSyntaxes()) {
			List<INode> syntaxNodes = getNodesFor(transitionNodes, syntax);
			if (match_definition_DefKeyword_0_0_or_DefineKeyword_0_1.equals(syntax))
				emit_definition_DefKeyword_0_0_or_DefineKeyword_0_1(semanticObject, getLastNavigableState(), syntaxNodes);
			else if (match_expression___IDTerminalRuleCall_1_0_EqualsSignKeyword_1_1__a.equals(syntax))
				emit_expression___IDTerminalRuleCall_1_0_EqualsSignKeyword_1_1__a(semanticObject, getLastNavigableState(), syntaxNodes);
			else acceptNodes(getLastNavigableState(), syntaxNodes);
		}
	}

	/**
	 * Ambiguous syntax:
	 *     'define' | 'def'
	 *
	 * This ambiguous syntax occurs at:
	 *     (rule start) (ambiguity) def=ID
	 */
	protected void emit_definition_DefKeyword_0_0_or_DefineKeyword_0_1(EObject semanticObject, ISynNavigable transition, List<INode> nodes) {
		acceptNodes(transition, nodes);
	}
	
	/**
	 * Ambiguous syntax:
	 *     (ID '=')*
	 *
	 * This ambiguous syntax occurs at:
	 *     (rule start) (ambiguity) 'if' infix+=expInfix
	 *     (rule start) (ambiguity) infix+=expInfix
	 */
	protected void emit_expression___IDTerminalRuleCall_1_0_EqualsSignKeyword_1_1__a(EObject semanticObject, ISynNavigable transition, List<INode> nodes) {
		acceptNodes(transition, nodes);
	}
	
}
